package com.caradvice.service;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Map;

/**
 * Tumme upp/ner på rekommenderade bilar. Ren JdbcTemplate utan JPA-entitet
 * (samma mönster som new_car_price) — nya JPA-entiteter kraschar prod-boot
 * eftersom ddl-auto=validate inte skapar tabeller.
 */
@Service
public class FeedbackService {

    private static final int MAX_TITLE_LENGTH = 200;

    private final JdbcTemplate jdbc;

    public FeedbackService(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    public void ensureTable() {
        // GENERATED ... AS IDENTITY är portabelt (Postgres 10+ och H2 2.x), till skillnad från BIGSERIAL
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS recommendation_feedback (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                car_title VARCHAR(200) NOT NULL,
                vote SMALLINT NOT NULL,
                created_at TIMESTAMP NOT NULL
            )
            """);
    }

    /** @return true om rösten sparades, false vid ogiltig input */
    public boolean save(String carTitle, String vote) {
        int v = voteValue(vote);
        if (v == 0 || carTitle == null || carTitle.isBlank() || carTitle.length() > MAX_TITLE_LENGTH) return false;
        jdbc.update("INSERT INTO recommendation_feedback(car_title, vote, created_at) VALUES (?,?,?)",
                carTitle.trim(), v, LocalDateTime.now(ZoneOffset.UTC));
        return true;
    }

    /** "up" → 1, "down" → -1, allt annat → 0 (ogiltig) */
    static int voteValue(String vote) {
        if ("up".equalsIgnoreCase(vote)) return 1;
        if ("down".equalsIgnoreCase(vote)) return -1;
        return 0;
    }

    /** Bilar med tydligt negativ nettofeedback (netto ≤ -minNet), värst först. */
    public List<String> dislikedCars(int minNet, int maxCars) {
        return jdbc.queryForList("""
            SELECT car_title FROM recommendation_feedback
            GROUP BY car_title
            HAVING SUM(vote) <= ?
            ORDER BY SUM(vote) ASC, car_title
            """, String.class, -minNet)
            .stream().limit(maxCars).toList();
    }

    /** @return antal raderade röster för bilen (exakt titelmatchning) */
    public int deleteByCarTitle(String carTitle) {
        if (carTitle == null || carTitle.isBlank()) return 0;
        return jdbc.update("DELETE FROM recommendation_feedback WHERE car_title = ?", carTitle.trim());
    }

    public List<Map<String, Object>> summary() {
        return jdbc.queryForList("""
            SELECT car_title,
                   SUM(CASE WHEN vote = 1 THEN 1 ELSE 0 END) AS upvotes,
                   SUM(CASE WHEN vote = -1 THEN 1 ELSE 0 END) AS downvotes,
                   COUNT(*) AS total
            FROM recommendation_feedback
            GROUP BY car_title
            ORDER BY total DESC, car_title
            """);
    }
}
